- name: Deploy container
  hosts: tencent-vm
  become: yes
  vars:
    project_name: "{{ lookup('env', 'PROJECT_NAME') | default('app') }}"
    image_name: "{{ lookup('env', 'IMAGE_NAME') | default('REPO:latest') }}"
    tar_path:   "{{ lookup('env', 'IMAGE_TAR')  | default('/tmp/docker.tar') }}"
  tasks:
    - name: Check if Docker image tarball exists
      stat:
        path: "{{ tar_path }}"
      register: tarball_stat
      delegate_to: localhost

    - name: Fail if Docker image tarball is missing
      fail:
        msg: "Docker image tarball not found at {{ tar_path }}"
      when: not tarball_stat.stat.exists

    - name: Copy Docker image tarball
      copy:
        src: "{{ tar_path }}"
        dest: /tmp/docker.tar
        mode: '0644'

    - name: Load image
      shell: docker load --input /tmp/docker.tar

    - name: Stop and remove old container
      docker_container:
        name: "{{ project_name }}"
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Run new container
      docker_container:
        name: "{{ project_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "7443:7443"
        detach: yes