# .github/workflows/security.yml
name: Dependency Alerts
on:
  workflow_call: 

jobs:
  dep-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/dependency-review-action@v3
        with:
          fail-on-severity: high