# .github/workflows/security.yml
name: Dependency Alerts

on:
  workflow_call:
    secrets:
      PAT_GITHUB_TOKEN:
        required: true

jobs:
  dep-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/dependency-review-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        with:
          fail-on-severity: high